laravel_2_Crud/laravel-Crud/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/categorie', 'CategorieController')->middleware('auth');

Route::resource('/product', 'ProductController');

laravel_2_Crud/laravel-Crud/app/Categorie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
    protected $fillable = [
        'name',
    ];
}

laravel_2_Crud/laravel-Crud/app/Product.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
   

    public function categorie(){
        return $this->belongsTo('App\Categorie');
    }

  
    public function users(){
        return $this->belongsToMany(User::class, 'user_products', 'product_id', 'user_id');
    }
       
}

laravel_2_Crud/laravel-Crud/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

laravel_2_Crud/laravel-Crud/app/UserProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserProduct extends Model
{
    //
}

laravel_2_Crud/laravel-Crud/app/Http/Controllers/CategorieController.php
<?php

namespace App\Http\Controllers;
use App\Categorie;
use Illuminate\Http\Request;

class CategorieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $categories = Categorie::all();
        return view('categorie.categorie', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categorie.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:categories|max:20',
        ]);

        Categorie::create($request->all());

        return redirect()->route('categorie.index')
            ->with('success', 'Categorie created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categorie = Categorie::find($id);
        return view('categorie.detail', ['categorie' => $categorie]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categorie = Categorie::find($id);
        return view('categorie.edit', ['categorie' => $categorie]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categorie = Categorie::find($id);

        $request->validate([
            'name' => 'required',
        ]);

        $categorie->update($request->all());

        return redirect()->route('categorie.index')
            ->with('success', 'Categorie updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categorie = Categorie::find($id);
        $categorie->delete();

        return redirect()->route('categorie.index')
            ->with('success', 'Categorie deleted successfully');
    }
}

laravel_2_Crud/laravel-Crud/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

laravel_2_Crud/laravel-Crud/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\Product;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $user = User::find(Auth::user()->id);
       
        $products = Product::whereHas('users', function($q) use($user) {
            $q->where('user_id', $user->id);
        })->get();

        return view('home', ['products' => $products]);
    }
}

laravel_2_Crud/laravel-Crud/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Categorie;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::groupBy('categorie_id')->get();
        return view('product.product', ['products' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categorie::all();
        return view('product.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'categorie_id' => 'required'
        ]);

        $categorie = Categorie::find($request->categorie_id);

        $product = new Product();
        $product->name = $request->name;
        $product->categorie = $categorie;

        Product::create($product);


        return redirect()->route('Product.index')
            ->with('success', 'Product created successfully.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

laravel_2_Crud/laravel-Crud/resources/views/categorie/categorie.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <h3 class="title-page">Categories</h3>
   <a href="{{ route('categorie.create') }}" class="btn btn-primary"> Create </a>

   @if ($message = Session::get('success'))
        <div class="alert alert-success mt-3">
            <p>{{ $message }}</p>
        </div>
    @endif

   <table class="table mt-5">
        <thead>
            <tr>
                <th>Categorie</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach ($categories as $categorie)
            <tr>
                <td>{{ $categorie->name }}</td>
                <td> 
                  <a href="{{ route('categorie.show', $categorie->id) }}" class="btn btn-info"> Details </a>
            </tr>
        @endforeach
        </tbody>
   </table>
</div>
@endsection

laravel_2_Crud/laravel-Crud/resources/views/categorie/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <h3 class="title-page mb-5">
        <a href="{{ route('categorie.index') }}"> Categorie </a> / new
    </h3>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('categorie.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>
@endsection

laravel_2_Crud/laravel-Crud/resources/views/categorie/detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <h3 class="title-page mb-5">
        <a href="{{ route('categorie.index') }}"> Categorie </a> / 
        {{ $categorie->name }} 
    </h3>
    <form action="{{ route('categorie.destroy', $categorie->id) }}" method="POST">
    <a href="{{ route('categorie.edit', $categorie->id) }}" class="btn btn-primary"> Update </a>
    @csrf
    @method('DELETE')
        <button type="submit" class="btn btn-danger"> Delete </button>
    </form>
</div>
@endsection

laravel_2_Crud/laravel-Crud/resources/views/categorie/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <h3 class="title-page mb-5">
        <a href="{{ route('categorie.index') }}"> Categorie </a> / 
        {{ $categorie->name }} 
    </h3>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('categorie.update', $categorie->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $categorie->name }}" class="form-control" placeholder="Name">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>
@endsection

laravel_2_Crud/laravel-Crud/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <h3 class="title-page">Products</h3>

   <table class="table mt-5">
        <thead>
            <tr>
                <th>Product</th>
                <th>Categorie</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach ($products as $product)
            <tr>
                <td>{{ $product->name }}</td>
                <td>{{ $product->categorie->name }}</td>
                <td> 
                  <a href="{{ route('product.show', $product->id) }}" class="btn btn-info"> Details </a>
            </tr>
        @endforeach
        </tbody>
   </table>
</div>
@endsection

laravel_2_Crud/laravel-Crud/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

laravel_2_Crud/laravel-Crud/resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <h3 class="title-page mb-5">
        <a href="{{ route('product.index') }}"> Product </a> / new
    </h3>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('product.store') }}" method="POST">
        @csrf
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" class="form-control" placeholder="Name">
                </div>
                <div class="form-group">
                    <strong>Categorie:</strong>
                    <select class="form-control" name="categorie_id">
                    @foreach ($categories as $categorie)
                        <option value="{{ $categorie->id }}"> {{ $categorie->name }}</option>
                    @endforeach
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
</div>
@endsection

laravel_2_Crud/laravel-Crud/resources/views/product/product.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <h3 class="title-page">Products</h3>

   <table class="table mt-5">
        <thead>
            <tr>
                <th>Product</th>
                <th>Categorie</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach ($products as $product)
            <tr>
                <td>{{ $product->name }}</td>
                <td>{{ $product->categorie->name }}</td>
                <td> 
                  <a href="{{ route('product.show', $product->id) }}" class="btn btn-info"> Details </a>
            </tr>
        @endforeach
        </tbody>
   </table>
</div>
@endsection